### PR TITLE
Fixes magic circle cost

### PR DESCRIPTION
**Pull request by UndeadNappist**
As per sr3, page 167. I'll update the helpfile later.

### CODE REVIEW

**Comment by luciensadi** [comment]
Where did you get the *100 from? What I'm reading on p167 is:
```The cost of creating a circle is negligible—its rating squared in nuyen for the paint or chalk.```

**Comment by UndeadNappist** [comment]
image

**Comment by luciensadi** [comment]
> \> exam circle
> Hermetic circles are the corner stone of a mage's summoning ritual. It is an elaborate design, drawn in chalk that takes up most of the floor space in the room.

Thanks for the PR, but this doesn't seem to be in line with the existing circles. If you want to try your hand at writing permanent circles, we could talk about that!

**Comment by UndeadNappist** [comment]
Full on permanency seems to be more of a factor of PGHQs and not for casual construction.

**Pull request closed without merging**
