### PR TITLE
Fold Argon2 password hashing changes from libsodium branch to master

### PR DESCRIPTION
**Pull request by luciensadi**
This PR brings in [Argon2](https://en.wikipedia.org/wiki/Argon2) to replace crypt(). This increases the resistance of stored passwords to brute-forcing.

**WARNING: IF YOU UPGRADE YOUR CODEBASE TO THIS PATCH, YOU MUST ALSO MODIFY YOUR DATABASE IN ACCORDANCE WITH `SQL/migration-libsodium.sql`. FAILURE TO DO SO WILL RESULT IN PASSWORDS NO LONGER SAVING FOR ALL CHARACTERS, AND MAY BREAK NEW CHARACTERS AS WELL.**

### CODE REVIEW

**Comment by luciensadi** [comment]
I could use a review on this PR, any community takers?

**Comment by jalles76** [comment]
Hi Lucien,
this branch segfaults for me:
````
./lucien_autorun
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from bin/awake...done.
(gdb) run
Starting program: /home/awake/AwakeMUD/bin/awake
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Oct 29 18:50:13 :: Using lib as data directory.
Oct 29 18:50:13 :: Running game on port 4000.
Oct 29 18:50:13 :: Setting player limit to 300 using rlimit.
Oct 29 18:50:13 :: Opening mother connection.
Oct 29 18:50:13 :: DBInit -- BEGIN.
Oct 29 18:50:13 :: Resetting the game time:
Oct 29 18:50:13 ::    Current Gametime: 1/21/2064 2:00.
Oct 29 18:50:13 :: Reading news, credits, help, bground, info & motds.
Oct 29 18:50:13 :: Loading fight messages.
Oct 29 18:50:13 :: Booting World.
Oct 29 18:50:13 :: Initializing libsodium for crypto functions.
Oct 29 18:50:13 :: Performing crypto performance and validation tests.
Oct 29 18:50:13 :: Testing hashing and verifying reproducibility of output.
Oct 29 18:50:14 :: $argon2i$v=19$m=131072,t=6,p=1$Q1ON2Tt117Hb2ADQPL65NA$oldPnMrYxRQAWrHSVrPZJInqxkkHRpddCpp8wo/Hes0

Program received signal SIGSEGV, Segmentation fault.
__strncmp_sse42 () at ../sysdeps/x86_64/multiarch/strcmp-sse42.S:164
164     ../sysdeps/x86_64/multiarch/strcmp-sse42.S: No such file or directory.
````

Current master compiles & runs (as far as I can tell) fine on Debian 9.

**Comment by jalles76** [comment]
Backtrace here:

````
Program received signal SIGSEGV, Segmentation fault.
__strncmp_sse42 () at ../sysdeps/x86_64/multiarch/strcmp-sse42.S:164
164     ../sysdeps/x86_64/multiarch/strcmp-sse42.S: No such file or directory.
(gdb) bt
#0  __strncmp_sse42 () at ../sysdeps/x86_64/multiarch/strcmp-sse42.S:164
#1  0x000055555573c7f2 in validate_password (password=0x55555578edb9 "8h4engowo)(WTWerhio*",
    hashed_password=0x7fffffffe9f0 "$argon2i$v=19$m=131072,t=6,p=1$9lgGUFVGw+EChyRcfRExaw$FjaLTCAJfgtYrCWbFg4I/N5MDXydZuyiXNDJun4nVEc") at security.cpp:115
#2  0x000055555573c508 in run_crypto_tests () at security.cpp:42
#3  0x00005555556cc917 in boot_world () at db.cpp:284
#4  0x00005555556ccb52 in DBInit () at db.cpp:358
#5  0x00005555555fbe37 in init_game (port=4000) at comm.cpp:355
#6  0x00005555555fb946 in main (argc=1, argv=0x7fffffffebe8) at comm.cpp:240
````

**Comment by luciensadi** [comment]
Thanks for the logs @jalles76 . For the benefit of future browsers, the issue was that he was running an older version of libsodium (1.0.11-2 vs 1.0.16), which selected Argon2i instead of Argon2id for hashing. This caused the Argon2 check to fail, which passed the long Argon2 hash into crypt() directly. This overflowed memory and caused the SIGSEGV above.

**Comment by luciensadi** [comment]
TODO before I'll merge this: Add some form of verification code that checks the width of the password column and errors out (or fixes it?) if it's not wide enough.

**Pull request merged**
